CREATE TABLE users (
    id INT(13) NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `name` VARCHAR(50) NOT NULL COMMENT 'user name',
    birthday DATE NOT NULL COMMENT 'user birthday',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;